parameters:
    app.allowed_locales_pattern: 'de|en|es|fr'
    app.dictionaries:
        - '%kernel.project_dir%/data/words.txt'
        - '%kernel.project_dir%/data/words.xml'
    app.mail_recipient: 'training@sensiolabs.com'
    locale: 'en'

services:
    # default configuration only applies for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            # these are the scalar arguments used by service constructors. Instead of defining
            # the 'arguments' option for each service, you can define all once in this file
            $recipient: '%app.mail_recipient%'
            $dictionaries: '%app.dictionaries%'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Game\WordList:
        calls:
            - { method: 'addLoader', arguments: ['@App\Game\Loader\TextFileLoader'] }
            - { method: 'addLoader', arguments: ['@App\Game\Loader\XmlFileLoader'] }

    App\Game\RunnerInterface: '@App\Game\Runner'

    App\Game\LoggedRunner:
        decorates: 'App\Game\Runner'
        arguments: ['@App\Game\LoggedRunner.inner', '@monolog.logger.hangman']



